# Generated by Django 5.2.9 on 2025-12-14 08:46

import apps.families.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='family name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('invite_code', models.CharField(db_index=True, default=apps.families.models.generate_invite_code, max_length=8, unique=True, verbose_name='invite code')),
                ('invite_code_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='invite code expires at')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='currency')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'family',
                'verbose_name_plural': 'families',
                'db_table': 'families',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', max_length=10, verbose_name='role')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('joined_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'family member',
                'verbose_name_plural': 'family members',
                'db_table': 'family_members',
                'ordering': ['-joined_at'],
            },
        ),
    ]
