# Generated by Django 5.2.9 on 2025-12-14 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_families', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='families.family', verbose_name='family'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_memberships', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['invite_code'], name='idx_family_invite'),
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['created_at'], name='idx_family_created'),
        ),
        migrations.AddIndex(
            model_name='familymember',
            index=models.Index(fields=['family', 'user'], name='idx_family_user'),
        ),
        migrations.AddIndex(
            model_name='familymember',
            index=models.Index(fields=['user', 'is_active'], name='idx_user_active'),
        ),
        migrations.AddIndex(
            model_name='familymember',
            index=models.Index(fields=['joined_at'], name='idx_member_joined'),
        ),
        migrations.AlterUniqueTogether(
            name='familymember',
            unique_together={('family', 'user')},
        ),
    ]
