# Generated by Django 5.2.9 on 2025-12-14 08:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='category name')),
                ('type', models.CharField(choices=[('food', 'Food & Groceries'), ('transport', 'Transport'), ('utilities', 'Utilities & Bills'), ('entertainment', 'Entertainment'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('clothing', 'Clothing'), ('housing', 'Housing'), ('other', 'Other')], db_index=True, default='other', max_length=20, verbose_name='category type')),
                ('is_default', models.BooleanField(default=False, verbose_name='is default category')),
                ('color', models.CharField(default='#808080', max_length=7, verbose_name='color')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='icon')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
                'ordering': ['type', 'name'],
            },
        ),
    ]
