# Generated by Django 5.2.9 on 2025-12-14 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('families', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_categories', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='category',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='families.family', verbose_name='family'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['family', 'type'], name='idx_cat_family_type'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['type'], name='idx_cat_type'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_default'], name='idx_cat_default'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('family', 'name')},
        ),
    ]
